#!/usr/bin/env bash
#
# bootstrap-deps.sh — GENERATED by `lhpc deps --script`; do NOT hand-edit (regenerate instead).
# Source manifest dependency revision: b21f7aeb4070
#
# Run ONCE on a fresh Raspberry Pi OS Trixie (arm64) image, BEFORE cloning/installing
# loraham-pi-control. MUST run as root: `sudo bash bootstrap-deps.sh` (the documented call).
# The script itself never invokes sudo — once root, every privileged command runs directly, so
# it works where sudo is absent, unconfigured, or cannot prompt (unattended runs). A non-root
# invocation refuses up front (exit 10) — EXCEPT `--dry-run` and -h/--help, which stay
# unprivileged on purpose: the pre-flight is read-only and zero-trust, meant to be vetted
# BEFORE the script is ever granted root. lhpc itself never runs privileged commands.
#
#   bootstrap-deps.sh --spi-mode <soft-cs|hardware-cs|skip> [--operator-user <name>] [--no-swapfile] [--swap-size <MB>] [--with-gui] [--keep-wifi-powersave]
#   bootstrap-deps.sh --dry-run        PRE-FLIGHT: simulate only, change nothing
#     soft-cs      software CS (/dev/spidev0.0): dtparam=spi=on + dtoverlay=spi0-0cs  (LoRaHAM Pi / Uputronics rigs, single-radio AND dual Uputronics: daemon + meshtasticd drive CS7/CS8 as GPIOs — the kernel must NOT claim CE0/CE1)
#     hardware-cs  kernel-driven CE0+CE1, no overlay: dtparam=spi=on only  (only for boards that really use kernel chip-selects; NOT for Uputronics — CE0/CE1=GPIO7/8 would collide with the daemon's GPIO chip-selects)
#     skip         no boot-config change (SPI already configured)
#     --no-swapfile      do NOT provision the small-RAM disk swapfile (see below)
#     --swap-size <MB>   swapfile size when provisioned (default 768)
# Exit codes: 2 usage · 3 conflicting SPI config · 4 required swap unprovisioned ·
#             5 --dry-run could not resolve · 6 --dry-run found graphical packages ·
#             7 hardware group grant failed · 8 system nginx.service could not be confirmed stopped ·
#             9 systemd unit files could not be inspected (fail-closed — a competing service
#             may be active) · 10 not running as root (run: sudo bash bootstrap-deps.sh ...).
#             Steps that can legitimately fail on a CLEAN
#             image (no packaged meshtasticd unit) are GUARDED — the script runs under
#             `set -e`, so an unguarded one would abort before this summary.
#     --dry-run          simulate the DEFAULT apt transaction and exit WITHOUT touching the
#                        system. Exits 0 only when the transaction resolves cleanly and pulls
#                        no graphical/audio stack; nonzero when it cannot be resolved or would
#                        install one. Run this FIRST on a fresh image — the package closure is
#                        then known before anything is installed, not discovered mid-install.
#     --with-gui         ALSO install the GUI-only dependencies (GTK/Tk) that the desktop components need. OMITTED BY DEFAULT: this script must never pull a graphical stack onto a headless image. It installs GUI application LIBRARIES only — never a desktop environment, display manager or X/Wayland server — and assumes you already run a graphical session.
#     --keep-wifi-powersave  Do NOT touch Wi-Fi settings. BY DEFAULT — but ONLY when the install actually runs over Wi-Fi (the default route's device is a NetworkManager TYPE=wifi device, or no route/type is determinable); a LAN-carried install leaves Wi-Fi untouched automatically — this script DISABLES Wi-Fi power-save on a NetworkManager-managed wlan interface, because on a Pi Zero 2W the brcmfmac Wi-Fi firmware drops (the interface can vanish until reboot) under a long build's sustained CPU load — which breaks a headless install over Wi-Fi. It writes ONE NetworkManager drop-in (revert: rm /etc/NetworkManager/conf.d/wifi-nopowersave.conf && systemctl restart NetworkManager). Pass this flag to leave Wi-Fi untouched (e.g. Ethernet, or you manage it yourself); a warning then explains the risk.
#
# The apt package set is IDENTICAL on a Pi Zero 2W and a Pi 5; only the SPI mode is hardware-
# specific. QEMU + PlatformIO are provisioned later by the MANAGED build (`lhpc build`), not here.
set -euo pipefail

usage() {
	echo "usage: bootstrap-deps.sh --spi-mode <soft-cs|hardware-cs|skip> [--operator-user <name>] [--no-swapfile] [--swap-size <MB>] [--with-gui] [--keep-wifi-powersave]" >&2
	echo "       bootstrap-deps.sh --dry-run   (simulate the default apt transaction; no changes)" >&2
}

SPI_MODE=""
OPERATOR_USER=""
NO_SWAPFILE=""
SWAP_SIZE_MB=""
WITH_GUI=""
KEEP_WIFI=""
DRY_RUN=""
while [ $# -gt 0 ]; do
	case "$1" in
		--spi-mode) SPI_MODE="${2:?--spi-mode needs a value}"; shift 2 ;;
		--operator-user) OPERATOR_USER="${2:?--operator-user needs a value}"; shift 2 ;;
		--no-swapfile) NO_SWAPFILE=1; shift ;;
		--with-gui) WITH_GUI=1; shift ;;
		--keep-wifi-powersave) KEEP_WIFI=1; shift ;;
		--dry-run) DRY_RUN=1; shift ;;
		--swap-size) SWAP_SIZE_MB="${2:?--swap-size needs a value (MB)}"; shift 2 ;;
		-h|--help) usage; exit 0 ;;
		*) echo "ERROR: unknown argument: $1" >&2; usage; exit 2 ;;
	esac
done

# --- --dry-run: simulate the DEFAULT apt transaction, change NOTHING -----------------------
# The blocker this guards against: the real package closure used to be discovered only while
# installing on hardware. `apt-get install -s` resolves it against the local apt database
# without touching the system, so a from-zero run can be vetted first. The GUI opt-in is NOT
# part of this verdict — the default transaction is what a headless image gets.
if [ -n "$DRY_RUN" ]; then
	echo "[bootstrap-deps] DRY RUN — simulating the default apt transaction; nothing is installed or changed."
	if ! command -v apt-get >/dev/null 2>&1; then
		echo "ERROR: dry-run: apt-get is not available — cannot simulate the transaction." >&2
		exit 5
	fi
	DRY_PKGS="build-essential ca-certificates cmake curl git libbluetooth-dev libgcrypt20-dev libglib2.0-dev libgpiod-dev libi2c-dev liblgpio-dev libncurses-dev libpixman-1-dev libslirp-dev libslirp0 libssl-dev libulfius-dev libusb-1.0-0-dev libuv1-dev libyaml-cpp-dev meson nginx ninja-build pkg-config python3 python3-pip python3-venv socat zlib1g-dev"
	# Simulate EXACTLY what the install below runs (same flags, same package set).
	# -o Dir::State::status=/dev/null resolves against an EMPTY installed-package
	# database, so the verdict is the FULL closure a fresh image would get, not the delta
	# for THIS machine. Without it a box that already has the packages reports a clean
	# transaction and the cascade a fresh install would pull stays invisible.
	if ! DRY_OUT="$(apt-get install -s -y --no-install-recommends -o Dir::State::status=/dev/null $DRY_PKGS 2>&1)"; then
		printf "%s\n" "$DRY_OUT" >&2
		echo "ERROR: dry-run: apt could not resolve the declared package set (see above)." >&2
		echo "       Run: sudo apt-get update  — a stale or incomplete package list is the usual cause." >&2
		exit 5
	fi
	printf "%s\n" "$DRY_OUT" | grep -E "^Inst " || true
	DRY_N="$(printf "%s\n" "$DRY_OUT" | grep -cE "^Inst " || true)"
	echo "[bootstrap-deps] the default transaction would install/upgrade ${DRY_N} package(s)."
	# Fail-closed denylist: a headless rig must never acquire a display or audio stack, whether
	# it arrives as a hard Depends or as a Recommends.
	DRY_BAD="$(printf '%s\n' "$DRY_OUT" | awk '/^Inst /{print $2}' | grep -E '^(libgtk-|libgdk-|python3-tk|tk[0-9]|libsdl|libx11|libxcb|libxext|libxrandr|libxcursor|libxi[0-9]|libxfixes|libxss|xserver-|xwayland|x11-common|xauth|libwayland-|libgbm|libdrm|libegl|libgl[0-9x]|mesa-|libllvm|libpulse|libasound|libinput|libxkbcommon|adwaita-|gnome-|kde-|xfce4|lxde|cups|fonts-)' | sort -u || true)"
	if [ -n "$DRY_BAD" ]; then
		echo "ERROR: dry-run: the default transaction would install graphical/audio packages:" >&2
		printf '  %s\n' $DRY_BAD >&2
		echo "       A headless install must pull none of these. Report this rather than proceeding." >&2
		exit 6
	fi
	echo "[bootstrap-deps] dry run OK — resolved cleanly, no GTK/Tk/SDL/X11/Wayland/Mesa/LLVM/PulseAudio/libinput/xkbcommon, no display server or desktop environment."
	[ -n "$WITH_GUI" ] && echo "[bootstrap-deps] note: --with-gui additionally installs the GUI-only packages on a real run; they are opt-in and not part of this verdict."
	exit 0
fi

# ROOT REQUIRED (exit 10) for everything EXCEPT -h/--help and --dry-run, which are answered
# above: the pre-flight is deliberately READ-ONLY and ZERO-TRUST — an operator vets what the
# script would install BEFORE ever granting it root. Every mutating path below runs as root:
# the documented call is `sudo bash bootstrap-deps.sh`, and the script never invokes sudo
# itself (internal sudo prefixes used to fail where sudo is absent, unconfigured, or cannot
# prompt — unattended runs). Operator resolution below is UNCHANGED: $OP comes from SUDO_USER
# (or --operator-user) and uid-0 operators are refused — root never receives group grants.
if [ "$(id -u)" -ne 0 ]; then
	echo "ERROR: bootstrap-deps.sh must run as root — run: sudo bash bootstrap-deps.sh ${SPI_MODE:+--spi-mode $SPI_MODE}" >&2
	echo "       (only --dry-run and -h/--help work unprivileged)" >&2
	exit 10
fi
# Historic call sites below carry a `sudo` prefix; the script is root (checked above), so route
# them through a no-op. A shell FUNCTION shadows PATH lookup, so this also works on systems
# with no sudo binary at all.
sudo() { "$@"; }

# Validate ALL options up front — BEFORE any apt / repository / boot-config / group mutation.
case "$SPI_MODE" in
	soft-cs|hardware-cs|skip) ;;
	"") echo "ERROR: --spi-mode is required (soft-cs | hardware-cs | skip)." >&2; usage; exit 2 ;;
	*) echo "ERROR: unknown --spi-mode: $SPI_MODE (soft-cs | hardware-cs | skip)." >&2; exit 2 ;;
esac
if [ -n "$SWAP_SIZE_MB" ]; then
	if ! printf "%s" "$SWAP_SIZE_MB" | grep -qE "^[1-9][0-9]*$"; then
		echo "ERROR: --swap-size must be a positive integer number of MB: $SWAP_SIZE_MB" >&2; exit 2
	fi
	# Digit CAP first: a 20-digit argument would overflow the `[ -gt ]` arithmetic below,
	# so bound the LENGTH before the value is ever compared numerically.
	if ! printf "%s" "$SWAP_SIZE_MB" | grep -qE "^[0-9]{1,5}$" \
			|| [ "$SWAP_SIZE_MB" -lt 64 ] || [ "$SWAP_SIZE_MB" -gt 16384 ]; then
		echo "ERROR: --swap-size out of range (64-16384 MB): $SWAP_SIZE_MB" >&2; exit 2
	fi
fi

# --- read-only pre-flight: reject a conflicting/blocked environment BEFORE any mutation ------
CONFIG_TXT="${CONFIG_TXT:-/boot/firmware/config.txt}"
case "$SPI_MODE" in
	soft-cs)
		if grep -qE "^dtparam=spi=on" "$CONFIG_TXT" 2>/dev/null && ! grep -qxF "dtoverlay=spi0-0cs" "$CONFIG_TXT" 2>/dev/null; then
			echo "ERROR: $CONFIG_TXT enables SPI without the soft-CS overlay (hardware-CS?) — refusing to add a conflicting overlay. Either add 'dtoverlay=spi0-0cs' to $CONFIG_TXT (soft-CS — the LoRaHAM Pi / Uputronics case), or re-run with --spi-mode hardware-cs if this rig really uses kernel chip-selects, or --spi-mode skip to leave the boot config alone." >&2; exit 3
		fi ;;
	hardware-cs)
		if grep -qxF "dtoverlay=spi0-0cs" "$CONFIG_TXT" 2>/dev/null; then
			echo "ERROR: $CONFIG_TXT has the soft-CS overlay (dtoverlay=spi0-0cs) — incompatible with hardware-cs (needs kernel CE0/CE1). Either remove that overlay line to use hardware chip-selects, or re-run with --spi-mode soft-cs (the LoRaHAM Pi / Uputronics case), or --spi-mode skip to leave the boot config alone." >&2; exit 3
		fi ;;
esac

# systemd must be queryable NOW (a broken/absent manager aborts BEFORE ~70 packages land,
# not after): the disable steps below need it to find a competing system nginx.service and
# any packaged meshtasticd.service. Fail CLOSED, up front, system untouched.
if ! systemctl list-unit-files --no-legend >/dev/null 2>&1; then
	echo "ERROR: cannot inspect systemd unit files (is this a systemd system, and is it reachable?). Bootstrap must check for a competing system nginx.service (and any packaged meshtasticd.service) before it can safely proceed — refusing to continue so the system stays untouched. Resolve systemd access and re-run." >&2
	exit 8
fi

# Operator for the group grants: explicit --operator-user, else SUDO_USER when run under
# sudo, else the invoking user. NEVER grant hardware groups to root; require a real account.
OP="$OPERATOR_USER"
if [ -z "$OP" ]; then
	if [ -n "${SUDO_USER:-}" ]; then OP="$SUDO_USER"; else OP="$(id -un)"; fi
fi
if [ -z "$OP" ] || [ "$OP" = "root" ]; then
	echo "ERROR: no non-root operator for group grants — re-run as the operator with sudo, or pass --operator-user <name>." >&2; exit 2
fi
if ! id -u "$OP" >/dev/null 2>&1; then
	echo "ERROR: --operator-user \"$OP\" is not a real account." >&2; exit 2
fi
if [ "$(id -u "$OP")" -eq 0 ]; then
	echo "ERROR: refusing to grant hardware groups to a uid-0 account (\"$OP\")." >&2; exit 2
fi

unit_present() {
	systemctl list-unit-files --no-legend >/dev/null 2>&1 || return 2   # systemd not queryable
	[ -n "$(systemctl list-unit-files --no-legend "$1" 2>/dev/null)" ]  # 0 present, 1 absent
}

# --- APT packages (merged; installed FIRST so curl/etc. exist before the blocks below) ----
# --no-install-recommends: Recommends are what turned a headless install into a desktop one.
# Nothing here needs them — e.g. git Recommends openssh-client, which Recommends xauth, which
# Depends on libX11. Only hard Depends are installed, so the closure stays display-free.
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    git \
    libbluetooth-dev \
    libgcrypt20-dev \
    libglib2.0-dev \
    libgpiod-dev \
    libi2c-dev \
    liblgpio-dev \
    libncurses-dev \
    libpixman-1-dev \
    libslirp-dev \
    libslirp0 \
    libssl-dev \
    libulfius-dev \
    libusb-1.0-0-dev \
    libuv1-dev \
    libyaml-cpp-dev \
    meson \
    nginx \
    ninja-build \
    pkg-config \
    python3 \
    python3-pip \
    python3-venv \
    socat \
    zlib1g-dev

# --- system nginx: keep the package, disable the ROOT service ----------------------------
nginx_rc=0; unit_present nginx.service || nginx_rc=$?
case "$nginx_rc" in
	0)
		# Only ANNOUNCE a change if there is one: an already-disabled+inactive unit is
		# reported as such rather than claiming we 'disabled' it.
		if systemctl is-enabled --quiet nginx.service 2>/dev/null || systemctl is-active --quiet nginx.service 2>/dev/null; then
			if sudo systemctl disable --now nginx.service; then
				echo "[bootstrap-deps] disabled the system nginx.service (lhpc serves via the lhpc-nginx user unit; the nginx PACKAGE stays installed)."
			else
				echo "ERROR: could not stop/disable the system nginx.service. A root nginx still owns the web ports, so the lhpc frontend cannot bind them. Resolve this and re-run." >&2
				exit 8
			fi
		else
			echo "[bootstrap-deps] system nginx.service is already disabled — nothing to change."
		fi ;;
	1) echo "[bootstrap-deps] no system nginx.service present — nothing to disable." ;;
	2) echo "ERROR: could not inspect systemd unit files — cannot confirm the system nginx.service is stopped. Refusing to continue with a possibly-active root nginx holding the web ports." >&2; exit 8 ;;
esac

# --- GUI-only dependencies (opt-in: --with-gui) ---------------------------------------------
# NOT installed by default. These are the toolkit libraries the DESKTOP components need
# (voice's GTK app, the MeshCore Node Manager's Tk GUI). On a headless image installing them
# would drag in the whole X11/Wayland dev chain for software that can never render, so they
# are opt-in. This installs LIBRARIES ONLY — never a desktop, display manager or X/Wayland
# server: it assumes the machine already has a graphical session.
if [ -n "$WITH_GUI" ]; then
	sudo apt-get install -y \
		libasound2-dev \
		libcodec2-dev \
		libgtk-3-dev \
		python3-tk
else
	echo "[bootstrap-deps] GUI dependencies skipped (headless-safe default). On a machine with a display, re-run with --with-gui."
fi

# --- SPI / boot config (idempotent; only the chosen --spi-mode mutates config.txt) ----------
# The read-only CONFLICT check ran UP FRONT (before any mutation, item P); here we only APPEND
# the idempotent lines for the chosen mode. CONFIG_TXT was set in the pre-flight above.
add_cfg() {  # append $1 iff absent (idempotent)
	if ! grep -qxF "$1" "$CONFIG_TXT" 2>/dev/null; then printf "%s\n" "$1" | sudo tee -a "$CONFIG_TXT" >/dev/null; fi
}
case "$SPI_MODE" in
	soft-cs)
		add_cfg "dtparam=spi=on"
		add_cfg "dtoverlay=spi0-0cs" ;;
	hardware-cs)
		add_cfg "dtparam=spi=on" ;;
	skip) echo "[bootstrap-deps] SPI: skipped (no boot-config change)." ;;
esac

# --- swap: disk-backed OOM insurance for small-RAM builds (idempotent; skips when unneeded) --
# Deferred verdict: a REQUIRED-but-unprovisioned swap fails the run (exit 4) at the very
# END, so the apt/SPI/group work still lands and the operator gets one loud, actionable
# failure instead of losing a configured machine to a full SD card.
_SWAP_FAILED=""
_GROUPS_FAILED=""
if [ -n "$NO_SWAPFILE" ]; then
	echo "[bootstrap-deps] swap: skipped (--no-swapfile)."
else
	SWAPFILE="${LHPC_SWAPFILE:-/var/swap.lhpc}"
	MEMINFO="${MEMINFO:-/proc/meminfo}"
	SWAPS="${SWAPS:-/proc/swaps}"
	FSTAB="${FSTAB:-/etc/fstab}"
	SWAP_TARGET_MB="${SWAP_SIZE_MB:-768}"
	SWAP_FSTAB_LINE="$SWAPFILE none swap sw,pri=10 0 0"
	_memmb=$(( $(awk '/^MemTotal:/{m=$2} END{print m+0}' "$MEMINFO" 2>/dev/null || echo 0) / 1024 ))
	# disk-backed swap only — zram is compressed RAM (no real backing store), so EXCLUDE it: an
	# OOM can happen with zram present (it did — 414Mi zram, 78Mi used, at the kill). OUR OWN
	# file is excluded too: "does this host still need us?" must not be answered by our own swap.
	_diskswap_mb=$(( $(awk -v f="$SWAPFILE" 'NR>1 && $1 !~ /zram/ && $1 != f {s+=$3} END{print s+0}' "$SWAPS" 2>/dev/null || echo 0) / 1024 ))
	# REQUIRED = this host cannot be trusted to build without OUR disk swap. Required-but-
	# missing is a HARD failure; --no-swapfile is the operator's only way to proceed without it.
	_swap_required=""
	if [ "$_memmb" -lt 600 ] && [ "$_diskswap_mb" -lt "$SWAP_TARGET_MB" ]; then _swap_required=1; fi
	# ACTIVE is the ONLY proof the swap does anything, and every lookup matches the FIRST FIELD
	# exactly: a substring/`grep -F` test also matches a commented-out line, a longer path
	# (/var/swap.lhpc.old) or a mount option — which is how an inactive swap got reported as
	# 'already present'.
	_swap_active() { awk -v f="$SWAPFILE" 'NR>1 && $1 == f {hit=1} END{exit !hit}' "$SWAPS" 2>/dev/null; }
	_fstab_declared() { awk -v f="$SWAPFILE" '$1 == f {hit=1} END{exit !hit}' "$FSTAB" 2>/dev/null; }
	# EXACTLY ONE canonical entry. A first-field match with the WRONG options, or two matches,
	# is NOT a valid declaration — it is rewritten. Anything else (comment, .old path) is not ours.
	_fstab_canonical() {
		awk -v f="$SWAPFILE" -v l="$SWAP_FSTAB_LINE" '$1 == f {n++; if ($0 == l) ok++} END{exit !(n == 1 && ok == 1)}' "$FSTAB" 2>/dev/null
	}
	# lstat, not stat: [ -L ] is the ONLY test that does NOT follow the link, and it must come
	# FIRST because [ -e ]/[ -f ]/[ -d ] all resolve. A symlink, directory, FIFO, socket or
	# device node at the swap path is a mistake or an attack (chmod 600 + mkswap would land on
	# an operator-chosen target). Refuse WITHOUT touching it — no chmod, no rm, no mkswap.
	_swap_leaf_ok() {
		if [ -L "$SWAPFILE" ]; then
			echo "[bootstrap-deps] swap: $SWAPFILE is a SYMLINK — refusing to touch it (remove it by hand)." >&2; return 1
		fi
		if [ ! -e "$SWAPFILE" ]; then return 0; fi
		if [ -d "$SWAPFILE" ]; then
			echo "[bootstrap-deps] swap: $SWAPFILE is a DIRECTORY — refusing to touch it (remove it by hand)." >&2; return 1
		fi
		if [ ! -f "$SWAPFILE" ]; then
			echo "[bootstrap-deps] swap: $SWAPFILE is not a regular file (FIFO/socket/device?) — refusing to touch it." >&2; return 1
		fi
		return 0
	}
	# TRANSACTIONAL fstab publication. `tee -a` can neither remove a stale/duplicate/wrong-
	# option line nor survive an interruption (a half-written line can make the next boot
	# unmountable). Build the WHOLE file in a same-directory temp, fsync it, then rename over
	# the original and fsync the directory. NEVER follow a symlink: this script is privileged,
	# so a planted/configured link would let it overwrite an arbitrary target.
	_fstab_publish() {
		if [ -L "$FSTAB" ]; then
			echo "[bootstrap-deps] swap: $FSTAB is a SYMLINK — refusing to publish through it." >&2; return 1
		fi
		if [ -e "$FSTAB" ] && [ ! -f "$FSTAB" ]; then
			echo "[bootstrap-deps] swap: $FSTAB is not a regular file — refusing to publish." >&2; return 1
		fi
		_ftmp="$(sudo mktemp "$(dirname "$FSTAB")/.fstab.lhpc.XXXXXX")" || return 1
		if [ -f "$FSTAB" ]; then
			# cp carries mode+ownership onto the 0600 root-owned temp; the filter then rewrites
			# its CONTENT: every EXACT first-field match is dropped (stale options, duplicates),
			# while comments and longer paths keep their own first field and survive verbatim.
			if ! sudo cp --preserve=mode,ownership "$FSTAB" "$_ftmp"; then
				sudo rm -f "$_ftmp"; return 1
			fi
			if ! sudo awk -v f="$SWAPFILE" '$1 != f' "$FSTAB" | sudo tee "$_ftmp" >/dev/null; then
				sudo rm -f "$_ftmp"; return 1
			fi
		elif ! sudo chmod 644 "$_ftmp"; then
			sudo rm -f "$_ftmp"; return 1
		fi
		if ! printf "%s\n" "$SWAP_FSTAB_LINE" | sudo tee -a "$_ftmp" >/dev/null; then
			sudo rm -f "$_ftmp"; return 1
		fi
		# Durable BEFORE the rename: a power loss must not publish an empty/partial fstab.
		if ! sudo sync "$_ftmp"; then sudo rm -f "$_ftmp"; return 1; fi
		if ! sudo mv -f "$_ftmp" "$FSTAB"; then sudo rm -f "$_ftmp"; return 1; fi
		sudo sync "$(dirname "$FSTAB")" || true   # dir entry durable (best-effort)
	}
	# Fresh allocation NEVER writes to the final path: a UNIQUE same-directory temp is
	# allocated, chmod 600'd, formatted and FSYNCED, and only a complete, valid swap image is
	# renamed into place. An interrupted run leaves an inert .swap.lhpc.XXXXXX, never a
	# half-formatted $SWAPFILE that the next run would try to swapon.
	_swap_alloc_temp() {
		_stmp="$(sudo mktemp "$(dirname "$SWAPFILE")/.swap.lhpc.XXXXXX")" || return 1
		if ! sudo fallocate -l "${SWAP_TARGET_MB}M" "$_stmp" 2>/dev/null; then
			if ! sudo dd if=/dev/zero of="$_stmp" bs=1M count="$SWAP_TARGET_MB" status=none; then
				sudo rm -f "$_stmp"; return 1
			fi
		fi
		if ! sudo chmod 600 "$_stmp"; then sudo rm -f "$_stmp"; return 1; fi
		if ! sudo mkswap "$_stmp" >/dev/null; then sudo rm -f "$_stmp"; return 1; fi
		if ! sudo sync "$_stmp"; then sudo rm -f "$_stmp"; return 1; fi
		printf "%s\n" "$_stmp"
	}
	# swapon stderr is NOT suppressed: its message ('read swap header failed', 'Device or
	# resource busy') is the operator's only clue. LOWER priority than zram (zram-generator
	# default 100): the file is overflow, zram stays the fast tier.
	_swap_install() {
		_new="$(_swap_alloc_temp)" || return 1
		if _swap_active; then
			if ! sudo swapoff "$SWAPFILE"; then
				echo "[bootstrap-deps] swap: $SWAPFILE is in use and swapoff failed — refusing to replace it." >&2
				sudo rm -f "$_new"; return 1
			fi
		fi
		if ! sudo mv -f "$_new" "$SWAPFILE"; then sudo rm -f "$_new"; return 1; fi
		sudo sync "$(dirname "$SWAPFILE")" || true
		sudo swapon -p 10 "$SWAPFILE"
	}
	_provision=""
	_swap_state="fail"
	if ! _swap_leaf_ok; then
		_swap_state="refused"
	elif _swap_active; then
		_swap_state="active"
	elif [ -f "$SWAPFILE" ] || _fstab_declared; then
		# Declared/allocated but NOT active — an earlier run interrupted between allocate and
		# swapon, or a stale fstab line. Try ONE in-place activation (cheapest, no SD writes);
		# else (re)create below. A successful reactivation STILL has to pass the fstab check.
		if [ ! -f "$SWAPFILE" ]; then
			# fstab still DECLARES the swapfile but the file itself is gone (deleted leftover). A
			# swapon here can ONLY print 'cannot open ... No such file or directory' — an expected
			# probe result, not a failure — so skip it and recreate rather than leak a scary line.
			# This is scoped to the file-absent case ONLY: P1a's unsuppressed swapon errors stay
			# unsuppressed on the REAL activation attempts (reactivate below, and _swap_install).
			echo "[bootstrap-deps] swap: fstab entry pointed at a missing file — recreating."
			_provision="reuse"
		elif sudo swapon -p 10 "$SWAPFILE" && _swap_active; then
			_swap_state="reactivated"
		else
			_provision="reuse"
		fi
	elif [ "$_memmb" -ge 600 ]; then
		_swap_state="skip-ram"
	elif [ "$_diskswap_mb" -ge "$SWAP_TARGET_MB" ]; then
		_swap_state="skip-disk"
	else
		_provision="fresh"
	fi
	if [ -n "$_provision" ]; then
		_swapdir="$(dirname "$SWAPFILE")"
		_freemb=$(( $(df -Pk "$_swapdir" 2>/dev/null | awk 'NR==2{f=$4} END{print f+0}' || echo 0) / 1024 ))
		# The image is built ALONGSIDE any existing file, so a FRESH run needs 2x the target
		# (image + headroom) and a REUSE needs 1x (the old file's blocks are charged until mv).
		if [ "$_provision" = "fresh" ]; then _need_mb=$(( SWAP_TARGET_MB * 2 )); else _need_mb="$SWAP_TARGET_MB"; fi
		if [ "$_freemb" -lt "$_need_mb" ]; then
			echo "[bootstrap-deps] swap: only ${_freemb}MB free on $_swapdir; need >= ${_need_mb}MB — refusing to fill the card." >&2
		elif _swap_install || _swap_install; then
			# ONE recreate: a truncated/corrupt leftover cannot be formatted in place.
			_swap_state="created"
		fi
	fi
	# SUCCESS = ACTIVE **AND** PERSISTENTLY DECLARED. That conjunction is what makes an
	# interruption after swapon but before fstab publication self-repair: the next run finds
	# it active, finds no canonical entry, and publishes one.
	case "$_swap_state" in
		active|reactivated|created)
			if _fstab_canonical || _fstab_publish; then
				case "$_swap_state" in
					created) echo "[bootstrap-deps] swap: created $SWAPFILE (${SWAP_TARGET_MB}MB, priority 10 — below zram)." ;;
					reactivated) echo "[bootstrap-deps] swap: already present ($SWAPFILE — reactivated)." ;;
					*) echo "[bootstrap-deps] swap: already present and active ($SWAPFILE)." ;;
				esac
			else
				echo "[bootstrap-deps] swap: $SWAPFILE is ACTIVE but $FSTAB could not be updated — it will NOT survive a reboot." >&2
				if [ -n "$_swap_required" ]; then _SWAP_FAILED=1; fi
			fi
			;;
		skip-ram) echo "[bootstrap-deps] swap: skipped (MemTotal ${_memmb}MB >= 600MB — enough RAM)." ;;
		skip-disk) echo "[bootstrap-deps] swap: skipped (disk-backed swap ${_diskswap_mb}MB already >= ${SWAP_TARGET_MB}MB target)." ;;
		*)
			echo "[bootstrap-deps] swap: FAILED to activate $SWAPFILE — builds on this machine may OOM" >&2
			if [ -n "$_swap_required" ]; then _SWAP_FAILED=1; fi
			;;
	esac
fi

# --- Wi-Fi power-save (default: DISABLE when the install runs over Wi-Fi; LAN install: leave
# --- untouched; --keep-wifi-powersave: never touch) ------------------------------------------
WIFI_PSAVE_CONF="${WIFI_PSAVE_CONF:-/etc/NetworkManager/conf.d/wifi-nopowersave.conf}"
# ONE nmcli call feeds presence, device pick AND default-route classification — all TYPE-based,
# never a wlan* name glob (predictable-naming Wi-Fi like wlp2s0 must not be mis-read as LAN).
_NM_DEVS="$(nmcli -t -f DEVICE,TYPE device 2>/dev/null || true)"
WIFI_DEV="$(printf '%s\n' "$_NM_DEVS" | awk -F: '$2=="wifi"{print $1; exit}')"
WIFI_DEFROUTE_DEV="$(ip -o route show default 2>/dev/null | awk '{for(i=1;i<NF;i++) if ($i=="dev") {print $(i+1); exit}}' || true)"
WIFI_DEFROUTE_TYPE="$(printf '%s\n' "$_NM_DEVS" | awk -F: -v d="$WIFI_DEFROUTE_DEV" '$1==d{print $2; exit}')"
if [ -n "$KEEP_WIFI" ]; then
	echo "[bootstrap-deps] Wi-Fi: left untouched (--keep-wifi-powersave)."
	echo "[bootstrap-deps]   WARNING: with power-save ON, a Pi Zero 2W can DROP Wi-Fi (the wlan"
	echo "[bootstrap-deps]   interface may vanish until reboot) during a long build — a headless"
	echo "[bootstrap-deps]   install over Wi-Fi may stall. Omit this flag to let bootstrap disable it."
elif [ -z "$WIFI_DEV" ]; then
	echo "[bootstrap-deps] Wi-Fi: no NetworkManager-managed wlan interface — nothing to do (wired/other)."
elif [ -n "$WIFI_DEFROUTE_DEV" ] && [ -n "$WIFI_DEFROUTE_TYPE" ] && [ "$WIFI_DEFROUTE_TYPE" != "wifi" ]; then
	# LAN carries the install (default route classified non-wifi): the drop-protection rationale
	# does not apply — do NOT mutate an unrelated Wi-Fi setting. An absent route or an
	# unclassifiable device falls through to the disable path instead: mis-detection must never
	# REMOVE protection.
	echo "[bootstrap-deps] Wi-Fi: left untouched — the install runs over LAN (default route via $WIFI_DEFROUTE_DEV, type $WIFI_DEFROUTE_TYPE)."
	echo "[bootstrap-deps]   If this box will later run headless over Wi-Fi, disable power-save manually:"
	echo "[bootstrap-deps]   printf '[connection]\nwifi.powersave = 2\n' | sudo tee $WIFI_PSAVE_CONF && sudo systemctl restart NetworkManager"
else
	echo "[bootstrap-deps] Wi-Fi: DISABLING power-save on $WIFI_DEV (default)."
	echo "[bootstrap-deps]   Reason: brcmfmac Wi-Fi on a Pi Zero 2W crashes/drops under a long build"
	echo "[bootstrap-deps]   with power-save on; --keep-wifi-powersave leaves Wi-Fi untouched."
	# Persistent config, fail-closed: refuse a symlink/non-regular leaf (never write THROUGH it under
	# sudo); write a ROOT-OWNED same-dir temp (sudo mktemp), chmod 0644, atomically rename into place,
	# and clean the temp up on ANY failure after creation. _persisted tracks success so the live-apply
	# report below never promises "after reboot" when nothing was actually written.
	_persisted=0
	if [ -L "$WIFI_PSAVE_CONF" ] || { [ -e "$WIFI_PSAVE_CONF" ] && [ ! -f "$WIFI_PSAVE_CONF" ]; }; then
		echo "[bootstrap-deps]   WARNING: $WIFI_PSAVE_CONF is a symlink or non-regular file - NOT touching it; power-save config left as-is." >&2
	else
		sudo mkdir -p "$(dirname "$WIFI_PSAVE_CONF")" 2>/dev/null || true
		if _wtmp="$(sudo mktemp "$(dirname "$WIFI_PSAVE_CONF")/.wifi-nopowersave.XXXXXX")" \
				&& printf '[connection]\nwifi.powersave = 2\n' | sudo tee "$_wtmp" >/dev/null \
				&& sudo chmod 0644 "$_wtmp" \
				&& sudo mv -- "$_wtmp" "$WIFI_PSAVE_CONF"; then
			_persisted=1
			echo "[bootstrap-deps]   persistent config written: $WIFI_PSAVE_CONF (wifi.powersave=2)"
			echo "[bootstrap-deps]   REVERT: sudo rm $WIFI_PSAVE_CONF && sudo systemctl restart NetworkManager"
		else
			[ -n "${_wtmp:-}" ] && sudo rm -f -- "$_wtmp"
			echo "[bootstrap-deps]   WARNING: could not write $WIFI_PSAVE_CONF - power-save NOT persisted." >&2
		fi
	fi
	# Live apply (best-effort), reported SEPARATELY. "after reboot" is promised ONLY when the config
	# was actually persisted; if neither persistence nor the live op succeeded, say so honestly.
	_live_ok=1
	_wcon="$(nmcli -t -f NAME,DEVICE connection show --active 2>/dev/null | grep ":${WIFI_DEV}$" | cut -d: -f1 | head -1 || true)"
	if [ -n "$_wcon" ]; then sudo nmcli connection modify "$_wcon" wifi.powersave 2 >/dev/null 2>&1 || _live_ok=0; fi
	if command -v iw >/dev/null 2>&1; then sudo iw dev "$WIFI_DEV" set power_save off >/dev/null 2>&1 || _live_ok=0; fi
	if [ "$_live_ok" = 1 ]; then
		echo "[bootstrap-deps]   Wi-Fi power-save disabled now (live)."
	elif [ "$_persisted" = 1 ]; then
		echo "[bootstrap-deps]   Wi-Fi power-save NOT applied live - takes effect after the next reboot."
	else
		echo "[bootstrap-deps]   Wi-Fi power-save NOT applied live and NOT persisted - power-save is UNCHANGED (fix $WIFI_PSAVE_CONF, then re-run)." >&2
	fi
fi

# --- persistent journal (crash forensics survive reboots; Storage=auto honours the dir) ------
JOURNAL_DIR="${JOURNAL_DIR:-/var/log/journal}"
if [ ! -d "$JOURNAL_DIR" ]; then
	sudo mkdir -p "$JOURNAL_DIR" || { echo "ERROR: could not create $JOURNAL_DIR — persistent journal NOT enabled." >&2; exit 1; }
fi
# ACL fixup is best-effort: the directory alone already makes Storage=auto persistent.
sudo systemd-tmpfiles --create --prefix="$JOURNAL_DIR" 2>/dev/null || echo "[bootstrap-deps] WARNING: systemd-tmpfiles ACL adjustment failed — the journal is persistent but may carry default permissions." >&2
echo "[bootstrap-deps] persistent journal enabled (takes effect after the reboot)."

# --- hardware group membership (granted to the resolved operator, never root) ------------
if sudo usermod -aG spi,gpio "$OP"; then
	echo "[bootstrap-deps] granted spi,gpio to $OP — log out/in (or reboot) to take effect."
else
	echo "ERROR: could not grant spi,gpio to $OP — do those groups exist on this system? Rootless SPI/GPIO access will NOT work until this is resolved." >&2
	_GROUPS_FAILED=1
fi

# --- disable an OS-packaged service (lhpc manages its own) --------------------------------
unit_rc=0; unit_present meshtasticd.service || unit_rc=$?
case "$unit_rc" in
	0)
		sudo systemctl disable --now meshtasticd
		echo "[bootstrap-deps] disabled the OS-packaged meshtasticd (lhpc manages its own)." ;;
	1) echo "[bootstrap-deps] no packaged meshtasticd service present — nothing to disable." ;;
	2) echo "ERROR: could not inspect systemd unit files — cannot confirm a packaged meshtasticd is stopped. Refusing to continue." >&2; exit 9 ;;
esac

if [ -n "$_GROUPS_FAILED" ]; then
	echo "[bootstrap-deps] hardware group membership could not be granted (see above) — the rootless stacks cannot reach the radio until it is." >&2
	exit 7
fi
if [ -n "$_SWAP_FAILED" ]; then
	echo "[bootstrap-deps] swap was REQUIRED on this low-memory host but could not be provisioned (see above). Fix the reported problem and re-run, or pass --no-swapfile to proceed without it (builds may be OOM-killed)." >&2
	exit 4
fi
echo "[bootstrap-deps] done. Reboot (SPI/groups), then: clone loraham-pi-control, ./install.sh."
