#!/usr/bin/env bash
#
# bootstrap-deps.sh — GENERATED by `lhpc deps --script`; do NOT hand-edit (regenerate instead).
# Source manifest dependency revision: ea28b8fa797f
#
# Run ONCE on a fresh Raspberry Pi OS Trixie (arm64) image, BEFORE cloning/installing
# loraham-pi-control. Works BOTH as an ordinary user (it calls sudo internally) AND via
# `sudo bash bootstrap-deps.sh`. lhpc itself never runs privileged commands.
#
#   bootstrap-deps.sh --spi-mode <soft-cs|hardware-cs|skip> [--operator-user <name>] [--no-swapfile] [--swap-size <MB>]
#     soft-cs      meshtasticd software CS (/dev/spidev0.0): dtparam=spi=on + dtoverlay=spi0-0cs  (single-radio LoRaHAM Pi / Uputronics)
#     hardware-cs  hardware CE0+CE1, no overlay: dtparam=spi=on only  (e.g. dual Uputronics)
#     skip         no boot-config change (SPI already configured)
#     --no-swapfile      do NOT provision the small-RAM disk swapfile (see below)
#     --swap-size <MB>   swapfile size when provisioned (default 768)
#
# The apt package set is IDENTICAL on a Pi Zero 2W and a Pi 5; only the SPI mode is hardware-
# specific. QEMU + PlatformIO are provisioned later by the MANAGED build (`lhpc build`), not here.
set -euo pipefail

usage() {
	echo "usage: bootstrap-deps.sh --spi-mode <soft-cs|hardware-cs|skip> [--operator-user <name>] [--no-swapfile] [--swap-size <MB>]" >&2
}

SPI_MODE=""
OPERATOR_USER=""
NO_SWAPFILE=""
SWAP_SIZE_MB=""
while [ $# -gt 0 ]; do
	case "$1" in
		--spi-mode) SPI_MODE="${2:?--spi-mode needs a value}"; shift 2 ;;
		--operator-user) OPERATOR_USER="${2:?--operator-user needs a value}"; shift 2 ;;
		--no-swapfile) NO_SWAPFILE=1; shift ;;
		--swap-size) SWAP_SIZE_MB="${2:?--swap-size needs a value (MB)}"; shift 2 ;;
		-h|--help) usage; exit 0 ;;
		*) echo "ERROR: unknown argument: $1" >&2; usage; exit 2 ;;
	esac
done

# Validate ALL options up front — BEFORE any apt / repository / boot-config / group mutation.
case "$SPI_MODE" in
	soft-cs|hardware-cs|skip) ;;
	"") echo "ERROR: --spi-mode is required (soft-cs | hardware-cs | skip)." >&2; usage; exit 2 ;;
	*) echo "ERROR: unknown --spi-mode: $SPI_MODE (soft-cs | hardware-cs | skip)." >&2; exit 2 ;;
esac
if [ -n "$SWAP_SIZE_MB" ] && ! printf "%s" "$SWAP_SIZE_MB" | grep -qE "^[1-9][0-9]*$"; then
	echo "ERROR: --swap-size must be a positive integer number of MB: $SWAP_SIZE_MB" >&2; exit 2
fi

# Operator for the group grants: explicit --operator-user, else SUDO_USER when run under
# sudo, else the invoking user. NEVER grant hardware groups to root; require a real account.
OP="$OPERATOR_USER"
if [ -z "$OP" ]; then
	if [ -n "${SUDO_USER:-}" ]; then OP="$SUDO_USER"; else OP="$(id -un)"; fi
fi
if [ -z "$OP" ] || [ "$OP" = "root" ]; then
	echo "ERROR: no non-root operator for group grants — re-run as the operator with sudo, or pass --operator-user <name>." >&2; exit 2
fi
if ! id -u "$OP" >/dev/null 2>&1; then
	echo "ERROR: --operator-user \"$OP\" is not a real account." >&2; exit 2
fi
if [ "$(id -u "$OP")" -eq 0 ]; then
	echo "ERROR: refusing to grant hardware groups to a uid-0 account (\"$OP\")." >&2; exit 2
fi

if [ "$(id -u)" -ne 0 ] && ! sudo -n true 2>/dev/null; then
	echo "[bootstrap-deps] you may be prompted for sudo (system packages + boot config)." >&2
fi

# --- APT packages (merged; installed FIRST so curl/gpg/etc. exist before the blocks below) -
sudo apt-get update
sudo apt-get install -y \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    git \
    gnupg \
    libasound2-dev \
    libcodec2-dev \
    libgtk-3-dev \
    liblgpio-dev \
    libncurses-dev \
    libslirp0 \
    libssl-dev \
    nginx \
    python3 \
    python3-pip \
    python3-venv \
    socat \
    wget \
    xz-utils

# --- third-party apt repository (dedicated keyring + signed-by, HTTPS) -------------------
. /etc/os-release
sudo install -d -m 0755 /etc/apt/keyrings
curl -fsSL "https://download.opensuse.org/repositories/network:Meshtastic:beta/Debian_${VERSION_ID}/Release.key" | gpg --dearmor | sudo tee /etc/apt/keyrings/meshtastic-obs.gpg > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/meshtastic-obs.gpg] https://download.opensuse.org/repositories/network:/Meshtastic:/beta/Debian_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/meshtastic-obs.list
sudo apt update
sudo apt install -y meshtasticd

# --- SPI / boot config (idempotent; only the chosen --spi-mode mutates config.txt) ----------
CONFIG_TXT="${CONFIG_TXT:-/boot/firmware/config.txt}"
add_cfg() {  # append $1 iff absent (idempotent)
	if ! grep -qxF "$1" "$CONFIG_TXT" 2>/dev/null; then printf "%s\n" "$1" | sudo tee -a "$CONFIG_TXT" >/dev/null; fi
}
case "$SPI_MODE" in
	soft-cs)
		if grep -qE "^dtparam=spi=on" "$CONFIG_TXT" 2>/dev/null && ! grep -qxF "dtoverlay=spi0-0cs" "$CONFIG_TXT" 2>/dev/null; then
			echo "ERROR: $CONFIG_TXT enables SPI without the soft-CS overlay (hardware-CS?) — refusing a conflicting overlay. Resolve by hand." >&2; exit 3
		fi
		add_cfg "dtparam=spi=on"
		add_cfg "dtoverlay=spi0-0cs"
		;;
	hardware-cs)
		if grep -qxF "dtoverlay=spi0-0cs" "$CONFIG_TXT" 2>/dev/null; then
			echo "ERROR: $CONFIG_TXT has the soft-CS overlay — incompatible with hardware-cs (needs CE0/CE1). Resolve by hand." >&2; exit 3
		fi
		add_cfg "dtparam=spi=on"
		;;
	skip) echo "[bootstrap-deps] SPI: skipped (no boot-config change)." ;;
esac

# --- swap: disk-backed OOM insurance for small-RAM builds (idempotent; skips when unneeded) --
if [ -n "$NO_SWAPFILE" ]; then
	echo "[bootstrap-deps] swap: skipped (--no-swapfile)."
else
	SWAPFILE="${LHPC_SWAPFILE:-/var/swap.lhpc}"
	MEMINFO="${MEMINFO:-/proc/meminfo}"
	SWAPS="${SWAPS:-/proc/swaps}"
	FSTAB="${FSTAB:-/etc/fstab}"
	SWAP_TARGET_MB="${SWAP_SIZE_MB:-768}"
	_memmb=$(( $(awk '/^MemTotal:/{m=$2} END{print m+0}' "$MEMINFO" 2>/dev/null || echo 0) / 1024 ))
	# disk-backed swap only — zram is compressed RAM (no real backing store), so EXCLUDE it: an
	# OOM can happen with zram present (it did — 414Mi zram, 78Mi used, at the kill).
	_diskswap_mb=$(( $(awk 'NR>1 && $1 !~ /zram/ {s+=$3} END{print s+0}' "$SWAPS" 2>/dev/null || echo 0) / 1024 ))
	if [ -e "$SWAPFILE" ] || grep -qsF "$SWAPFILE" "$FSTAB"; then
		if ! grep -qsF "$SWAPFILE" "$SWAPS"; then sudo swapon "$SWAPFILE" 2>/dev/null || true; fi
		echo "[bootstrap-deps] swap: already present ($SWAPFILE)."
	elif [ "$_memmb" -ge 600 ]; then
		echo "[bootstrap-deps] swap: skipped (MemTotal ${_memmb}MB >= 600MB — enough RAM)."
	elif [ "$_diskswap_mb" -ge "$SWAP_TARGET_MB" ]; then
		echo "[bootstrap-deps] swap: skipped (disk-backed swap ${_diskswap_mb}MB already >= ${SWAP_TARGET_MB}MB target)."
	else
		_swapdir="$(dirname "$SWAPFILE")"
		_freemb=$(( $(df -Pk "$_swapdir" 2>/dev/null | awk 'NR==2{f=$4} END{print f+0}' || echo 0) / 1024 ))
		_need_mb=$(( SWAP_TARGET_MB * 2 ))
		if [ "$_freemb" -lt "$_need_mb" ]; then
			echo "[bootstrap-deps] swap: skipped (only ${_freemb}MB free on $_swapdir; need >= ${_need_mb}MB = 2x target — refusing to fill the card)." >&2
		else
			if ! sudo fallocate -l "${SWAP_TARGET_MB}M" "$SWAPFILE" 2>/dev/null; then
				sudo rm -f "$SWAPFILE"
				sudo dd if=/dev/zero of="$SWAPFILE" bs=1M count="$SWAP_TARGET_MB" status=none
			fi
			sudo chmod 600 "$SWAPFILE"
			sudo mkswap "$SWAPFILE" >/dev/null
			# LOWER priority than zram (zram-generator default 100): the file is overflow, zram stays fast.
			sudo swapon -p 10 "$SWAPFILE"
			if ! grep -qsF "$SWAPFILE" "$FSTAB"; then
				printf "%s\n" "$SWAPFILE none swap sw,pri=10 0 0" | sudo tee -a "$FSTAB" >/dev/null
			fi
			echo "[bootstrap-deps] swap: created $SWAPFILE (${SWAP_TARGET_MB}MB, priority 10 — below zram)."
		fi
	fi
fi

# --- hardware group membership (granted to the resolved operator, never root) ------------
sudo usermod -aG spi,gpio "$OP"
echo "[bootstrap-deps] granted spi,gpio to $OP — log out/in (or reboot) to take effect."

# --- disable the OS-managed service (lhpc manages its own) -------------------------------
sudo systemctl disable --now meshtasticd

echo "[bootstrap-deps] done. Reboot (SPI/groups), then: clone loraham-pi-control, ./install.sh."
