#!/usr/bin/env bash
#
# bootstrap-deps.sh — GENERATED by `lhpc deps --script`; do NOT hand-edit (regenerate instead).
# Source manifest dependency revision: ea28b8fa797f
#
# Run ONCE on a fresh Raspberry Pi OS Trixie (arm64) image, BEFORE cloning/installing
# loraham-pi-control. Works BOTH as an ordinary user (it calls sudo internally) AND via
# `sudo bash bootstrap-deps.sh`. lhpc itself never runs privileged commands.
#
#   bootstrap-deps.sh --spi-mode <soft-cs|hardware-cs|skip> [--operator-user <name>]
#     soft-cs      meshtasticd software CS (/dev/spidev0.0): dtparam=spi=on + dtoverlay=spi0-0cs  (single-radio LoRaHAM Pi / Uputronics)
#     hardware-cs  hardware CE0+CE1, no overlay: dtparam=spi=on only  (e.g. dual Uputronics)
#     skip         no boot-config change (SPI already configured)
#
# The apt package set is IDENTICAL on a Pi Zero 2W and a Pi 5; only the SPI mode is hardware-
# specific. QEMU + PlatformIO are provisioned later by the MANAGED build (`lhpc build`), not here.
set -euo pipefail

usage() {
	echo "usage: bootstrap-deps.sh --spi-mode <soft-cs|hardware-cs|skip> [--operator-user <name>]" >&2
}

SPI_MODE=""
OPERATOR_USER=""
while [ $# -gt 0 ]; do
	case "$1" in
		--spi-mode) SPI_MODE="${2:?--spi-mode needs a value}"; shift 2 ;;
		--operator-user) OPERATOR_USER="${2:?--operator-user needs a value}"; shift 2 ;;
		-h|--help) usage; exit 0 ;;
		*) echo "ERROR: unknown argument: $1" >&2; usage; exit 2 ;;
	esac
done

# Validate ALL options up front — BEFORE any apt / repository / boot-config / group mutation.
case "$SPI_MODE" in
	soft-cs|hardware-cs|skip) ;;
	"") echo "ERROR: --spi-mode is required (soft-cs | hardware-cs | skip)." >&2; usage; exit 2 ;;
	*) echo "ERROR: unknown --spi-mode: $SPI_MODE (soft-cs | hardware-cs | skip)." >&2; exit 2 ;;
esac

# Operator for the group grants: explicit --operator-user, else SUDO_USER when run under
# sudo, else the invoking user. NEVER grant hardware groups to root; require a real account.
OP="$OPERATOR_USER"
if [ -z "$OP" ]; then
	if [ -n "${SUDO_USER:-}" ]; then OP="$SUDO_USER"; else OP="$(id -un)"; fi
fi
if [ -z "$OP" ] || [ "$OP" = "root" ]; then
	echo "ERROR: no non-root operator for group grants — re-run as the operator with sudo, or pass --operator-user <name>." >&2; exit 2
fi
if ! id -u "$OP" >/dev/null 2>&1; then
	echo "ERROR: --operator-user \"$OP\" is not a real account." >&2; exit 2
fi
if [ "$(id -u "$OP")" -eq 0 ]; then
	echo "ERROR: refusing to grant hardware groups to a uid-0 account (\"$OP\")." >&2; exit 2
fi

if [ "$(id -u)" -ne 0 ] && ! sudo -n true 2>/dev/null; then
	echo "[bootstrap-deps] you may be prompted for sudo (system packages + boot config)." >&2
fi

# --- APT packages (merged; installed FIRST so curl/gpg/etc. exist before the blocks below) -
sudo apt-get update
sudo apt-get install -y \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    git \
    gnupg \
    libasound2-dev \
    libcodec2-dev \
    libgtk-3-dev \
    liblgpio-dev \
    libncurses-dev \
    libslirp0 \
    libssl-dev \
    nginx \
    python3 \
    python3-pip \
    python3-venv \
    socat \
    wget \
    xz-utils

# --- third-party apt repository (dedicated keyring + signed-by, HTTPS) -------------------
. /etc/os-release
sudo install -d -m 0755 /etc/apt/keyrings
curl -fsSL "https://download.opensuse.org/repositories/network:Meshtastic:beta/Debian_${VERSION_ID}/Release.key" | gpg --dearmor | sudo tee /etc/apt/keyrings/meshtastic-obs.gpg > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/meshtastic-obs.gpg] https://download.opensuse.org/repositories/network:/Meshtastic:/beta/Debian_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/meshtastic-obs.list
sudo apt update
sudo apt install -y meshtasticd

# --- SPI / boot config (idempotent; only the chosen --spi-mode mutates config.txt) ----------
CONFIG_TXT="${CONFIG_TXT:-/boot/firmware/config.txt}"
add_cfg() {  # append $1 iff absent (idempotent)
	if ! grep -qxF "$1" "$CONFIG_TXT" 2>/dev/null; then printf "%s\n" "$1" | sudo tee -a "$CONFIG_TXT" >/dev/null; fi
}
case "$SPI_MODE" in
	soft-cs)
		if grep -qE "^dtparam=spi=on" "$CONFIG_TXT" 2>/dev/null && ! grep -qxF "dtoverlay=spi0-0cs" "$CONFIG_TXT" 2>/dev/null; then
			echo "ERROR: $CONFIG_TXT enables SPI without the soft-CS overlay (hardware-CS?) — refusing a conflicting overlay. Resolve by hand." >&2; exit 3
		fi
		add_cfg "dtparam=spi=on"
		add_cfg "dtoverlay=spi0-0cs"
		;;
	hardware-cs)
		if grep -qxF "dtoverlay=spi0-0cs" "$CONFIG_TXT" 2>/dev/null; then
			echo "ERROR: $CONFIG_TXT has the soft-CS overlay — incompatible with hardware-cs (needs CE0/CE1). Resolve by hand." >&2; exit 3
		fi
		add_cfg "dtparam=spi=on"
		;;
	skip) echo "[bootstrap-deps] SPI: skipped (no boot-config change)." ;;
esac

# --- hardware group membership (granted to the resolved operator, never root) ------------
sudo usermod -aG spi,gpio "$OP"
echo "[bootstrap-deps] granted spi,gpio to $OP — log out/in (or reboot) to take effect."

# --- disable the OS-managed service (lhpc manages its own) -------------------------------
sudo systemctl disable --now meshtasticd

echo "[bootstrap-deps] done. Reboot (SPI/groups), then: clone loraham-pi-control, ./install.sh."
