"""Host application configuration: one TOML file, generated by LHPC.

The host app takes concrete values only — LHPC's config generation owns policy (which
preset, which band, identity/secret placement, GPS plan). RF presets are resolved here
so the manifest's `preset` enum keeps meaning the same thing it meant for meshcore-pi.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path

# Same presets the meshcore-pi integration exposed (values must stay in lockstep with
# the LoRaHAM daemon band plan; eu_uk_narrow matches the T-Deck MeshCore firmware).
RF_PRESETS = {
    "eu_uk_long": {
        "frequency": 869525000, "bandwidth": 250000, "spreading_factor": 11,
        "coding_rate": 5, "preamble": 16, "ldro": False,
        "txpower": 14, "txmaxpower": 20,
    },
    "eu_uk_medium": {
        "frequency": 869525000, "bandwidth": 250000, "spreading_factor": 10,
        "coding_rate": 5, "preamble": 16, "ldro": False,
        "txpower": 14, "txmaxpower": 20,
    },
    "eu_uk_narrow": {
        "frequency": 869618000, "bandwidth": 62500, "spreading_factor": 8,
        "coding_rate": 8, "preamble": 16, "ldro": False,
        "txpower": 14, "txmaxpower": 20,
    },
}

GPS_MODES = ("off", "fixed", "feed")

# LOCKSTEP with lhpc/core/meshcore_mode.py (the controller's copy of the same rule set; this
# package installs standalone into the stack venv, so the constants are duplicated by necessity).
MODES = ("chat", "chat+repeater", "repeater")
BEHAVIOURS = ("forward", "monitor", "no_tx")
DASHBOARD_PORT = 8000


def is_valid_lat_lon(lat: float, lon: float) -> bool:
    """One shared coordinate-validity rule for fixed config and the live feed."""
    return -90.0 <= lat <= 90.0 and -180.0 <= lon <= 180.0


class ConfigError(ValueError):
    """The host configuration is unusable; startup must fail, not limp."""


@dataclass
class HostConfig:
    # [companion]
    name: str = "pyMC"
    bind: str = ""          # empty = derive from allow
    allow: str = "127.0.0.1"
    port: int = 5000

    # [identity] — exactly one of key (inline hex, LHPC secret_file injection)
    # or key_file (path) must be set.
    key_file: str = ""
    key: str = ""

    # [radio]
    data_socket: str = "/tmp/lora868f.sock"
    config_socket: str = "/tmp/loraconf868.sock"
    frequency: int = 0
    bandwidth: int = 0
    spreading_factor: int = 0
    coding_rate: int = 0
    txpower: int = 14
    txmaxpower: int = 20
    preamble: int = 16
    syncword: int = 0x12
    ldro: bool = False
    crc: bool = True
    enable_tx: bool = True
    airtime: float = 10.0

    # [persistence]
    db: str = ""

    # [gps]
    gps_mode: str = "off"
    gps_lat: float = 0.0
    gps_lon: float = 0.0
    gps_socket: str = ""
    gps_stale_s: float = 60.0

    # [repeater] — `mode` selects the program; the rest is used only when it is not "chat".
    mode: str = "chat"
    repeater_name: str = ""
    repeater_key: str = ""
    repeater_behaviour: str = "forward"
    dashboard_password: str = ""
    repeater_state_dir: str = ""

    extra: dict = field(default_factory=dict)

    @property
    def repeater_on(self) -> bool:
        return self.mode != "chat"

    @property
    def companion_on(self) -> bool:
        return self.mode != "repeater"


def _table(doc: dict, name: str) -> dict:
    value = doc.get(name, {})
    if not isinstance(value, dict):
        raise ConfigError(f"[{name}] must be a table")
    return value


def _req_str(table: dict, key: str, section: str) -> str:
    value = table.get(key)
    if not isinstance(value, str) or not value:
        raise ConfigError(f"[{section}] {key} must be a non-empty string")
    return value


def _opt(table: dict, key: str, default, types, section: str):
    value = table.get(key, default)
    if isinstance(value, bool) and bool not in (types if isinstance(types, tuple) else (types,)):
        raise ConfigError(f"[{section}] {key} has the wrong type")
    if not isinstance(value, types):
        raise ConfigError(f"[{section}] {key} has the wrong type")
    return value


def load_config(path: str | Path) -> HostConfig:
    try:
        raw = Path(path).read_bytes()
    except OSError as exc:
        raise ConfigError(f"cannot read config {path}: {exc}") from exc
    try:
        doc = tomllib.loads(raw.decode("utf-8"))
    except (ValueError, UnicodeError) as exc:
        raise ConfigError(f"config {path} is not valid TOML: {exc}") from exc

    cfg = HostConfig()

    companion = _table(doc, "companion")
    cfg.name = _opt(companion, "name", cfg.name, str, "companion")
    cfg.allow = _opt(companion, "allow", cfg.allow, str, "companion")
    cfg.bind = _opt(companion, "bind", "", str, "companion")
    if not cfg.bind:
        # LHPC's exposure model: `allow` is the operator-facing source allow-list
        # (enforced by the managed firewall). Loopback-only allow keeps the bind
        # on loopback; anything wider requires a wide bind for the firewall to
        # have something to gate.
        cfg.bind = "127.0.0.1" if cfg.allow.strip() in ("", "127.0.0.1") else "0.0.0.0"
    cfg.port = _opt(companion, "port", cfg.port, int, "companion")
    if not 1 <= cfg.port <= 65535:
        raise ConfigError("[companion] port out of range")

    identity = _table(doc, "identity")
    cfg.key_file = _opt(identity, "key_file", "", str, "identity")
    cfg.key = _opt(identity, "key", "", str, "identity")
    # The chat identity is checked once the role is known (below): the Companion needs
    # exactly one of key/key_file; the pure repeater has no Companion and must carry neither.

    radio = _table(doc, "radio")
    preset = radio.get("preset")
    preset_values: dict = {}
    if preset is not None:
        if preset not in RF_PRESETS:
            raise ConfigError(
                "[radio] preset must be one of: " + ", ".join(sorted(RF_PRESETS))
            )
        preset_values = RF_PRESETS[preset]

    def radio_value(key, default, types):
        if key in radio:
            return _opt(radio, key, None, types, "radio")
        if key in preset_values:
            return preset_values[key]
        if default is None:
            raise ConfigError(f"[radio] {key} is required (directly or via preset)")
        return default

    cfg.data_socket = _opt(radio, "data_socket", cfg.data_socket, str, "radio")
    cfg.config_socket = _opt(radio, "config_socket", cfg.config_socket, str, "radio")
    cfg.frequency = radio_value("frequency", None, int)
    cfg.bandwidth = radio_value("bandwidth", None, int)
    cfg.spreading_factor = radio_value("spreading_factor", None, int)
    cfg.coding_rate = radio_value("coding_rate", None, int)
    cfg.txpower = radio_value("txpower", 14, int)
    cfg.txmaxpower = radio_value("txmaxpower", cfg.txpower, int)
    cfg.preamble = radio_value("preamble", 16, int)
    sync = radio.get("syncword", 0x12)
    if isinstance(sync, str):
        try:
            sync = int(sync, 0)
        except ValueError as exc:
            raise ConfigError("[radio] syncword must be an integer") from exc
    if isinstance(sync, bool) or not isinstance(sync, int):
        raise ConfigError("[radio] syncword must be an integer")
    cfg.syncword = sync
    cfg.ldro = radio_value("ldro", False, bool)
    cfg.crc = _opt(radio, "crc", True, bool, "radio")
    cfg.enable_tx = _opt(radio, "enable_tx", True, bool, "radio")
    cfg.airtime = float(_opt(radio, "airtime", 10.0, (int, float), "radio"))

    persistence = _table(doc, "persistence")
    cfg.db = _opt(persistence, "db", "", str, "persistence")

    gps = _table(doc, "gps")
    cfg.gps_lat = float(_opt(gps, "lat", 0.0, (int, float), "gps"))
    cfg.gps_lon = float(_opt(gps, "lon", 0.0, (int, float), "gps"))
    cfg.gps_socket = _opt(gps, "socket", "", str, "gps")
    # Mode may be explicit, or inferred from what the controller rendered:
    # a socket -> live feed; coordinates -> fixed; neither -> off. This lets
    # LHPC's one GPS plan drive the mode without a dedicated placeholder.
    default_mode = "feed" if cfg.gps_socket else (
        "fixed" if ("lat" in gps and "lon" in gps) else "off")
    cfg.gps_mode = _opt(gps, "mode", default_mode, str, "gps")
    if cfg.gps_mode not in GPS_MODES:
        raise ConfigError("[gps] mode must be one of: " + ", ".join(GPS_MODES))
    cfg.gps_stale_s = float(_opt(gps, "stale_after_s", 60.0, (int, float), "gps"))
    if cfg.gps_mode == "fixed" and not is_valid_lat_lon(cfg.gps_lat, cfg.gps_lon):
        raise ConfigError("[gps] fixed position out of range")
    if cfg.gps_mode == "feed" and not cfg.gps_socket:
        raise ConfigError("[gps] feed mode requires socket")

    rep = _table(doc, "repeater")
    cfg.mode = _opt(rep, "role", cfg.mode, str, "repeater")
    if cfg.mode not in MODES:
        raise ConfigError("[repeater] role must be one of: " + ", ".join(MODES))
    cfg.repeater_name = _opt(rep, "name", "", str, "repeater").strip()
    cfg.repeater_key = _opt(rep, "key", "", str, "repeater")
    cfg.repeater_behaviour = _opt(rep, "behaviour", cfg.repeater_behaviour, str, "repeater")
    cfg.dashboard_password = _opt(rep, "admin_password", "", str, "repeater")
    cfg.repeater_state_dir = _opt(rep, "state_dir", "", str, "repeater")
    if cfg.companion_on:
        if bool(cfg.key_file) == bool(cfg.key):
            raise ConfigError("[identity] exactly one of key_file or key must be set")
    elif cfg.key or cfg.key_file:
        raise ConfigError("[identity] key/key_file are not used in the repeater role — "
                          "the pure repeater runs no Companion; remove them")
    if cfg.repeater_on:
        # The repeater is a DISTINCT MeshCore node with its own identity and login; in the chat
        # role these rows are simply ignored (the same file feeds every role).
        if not cfg.repeater_name or len(cfg.repeater_name.encode("utf-8")) > 31:
            raise ConfigError("[repeater] name is required in the repeater roles (1-31 UTF-8 bytes)")
        if not cfg.repeater_key:
            raise ConfigError("[repeater] key is required in the repeater roles")
        if cfg.repeater_behaviour not in BEHAVIOURS:
            raise ConfigError("[repeater] behaviour must be one of: " + ", ".join(BEHAVIOURS))
        if not cfg.dashboard_password:
            raise ConfigError("[repeater] admin_password is required in the repeater roles")
        if not cfg.repeater_state_dir:
            raise ConfigError("[repeater] state_dir is required in the repeater roles")

    return cfg
