"""Layered configuration.

Five concerns, kept strictly separate (see docs/operations.md):

  1. tracked defaults        config/defaults.toml          (in the dev checkout, tracked)
  2. known-good profiles     config/profiles.example.toml  (catalogue; runtime: profiles/)
  3. local operator overrides <runtime>/config/local.toml   (git-ignored, operator settings + callsign)
  4. local secrets           <runtime>/config/secrets.toml  (git-ignored, mode 0600)
  5. generated runtime state  <runtime>/state/              (never sole source of truth)

This module loads and merges layers 1+3 into an effective `Config`, and reads
secrets (layer 4) separately and lazily. It never writes secrets and never emits
them in status output. Callsign and other operator identity live ONLY in the
runtime-local layer, never in the tracked repo.
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from .paths import Paths

# Tracked defaults shipped with the controller.
_DEFAULTS_PATH = Path(__file__).resolve().parents[2] / "config" / "defaults.toml"


@dataclass(frozen=True)
class OperatorConfig:
    """Operator identity/settings — sourced ONLY from the runtime-local layer."""

    callsign: str = ""
    locator: str = ""

    @property
    def configured(self) -> bool:
        return bool(self.callsign)


@dataclass
class Config:
    """Effective configuration after merging defaults + local overrides."""

    values: dict = field(default_factory=dict)
    operator: OperatorConfig = field(default_factory=OperatorConfig)
    sources: dict = field(default_factory=dict)   # per-component runtime overrides
    remotes: dict = field(default_factory=dict)   # per-component GitHub remote overrides
    local_path: Path | None = None
    secrets_path: Path | None = None

    def get(self, section: str, key: str, default=None):
        return self.values.get(section, {}).get(key, default)


def _load_toml(path: Path) -> dict:
    if not path.is_file():
        return {}
    with path.open("rb") as fh:
        return tomllib.load(fh)


def _deep_merge(base: dict, override: dict) -> dict:
    out = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = _deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def load_config(paths: Paths, defaults_path: Path | None = None) -> Config:
    """Merge tracked defaults with the runtime-local override layer (read-only)."""
    defaults = _load_toml(defaults_path or _DEFAULTS_PATH)
    local_path = paths.runtime_root / "config" / "local.toml"
    local = _load_toml(local_path)
    merged = _deep_merge(defaults, local)

    op = merged.get("operator", {})
    operator = OperatorConfig(
        callsign=op.get("callsign", ""), locator=op.get("locator", "")
    )
    return Config(
        values=merged,
        operator=operator,
        sources=merged.get("sources", {}),
        remotes=local.get("remotes", {}),   # runtime-local only, never tracked
        local_path=local_path,
        secrets_path=paths.runtime_root / "config" / "secrets.toml",
    )


def load_secrets(paths: Paths) -> dict:
    """Read the local secrets layer (never tracked). Returns {} if absent."""
    return _load_toml(paths.runtime_root / "config" / "secrets.toml")


def _toml_value(kind: str, value: str) -> str:
    """Format a value as TOML scalar for a flat key update."""
    v = str(value)
    if kind in ("int", "float"):
        return v if v.strip() != "" else "0"
    if kind == "flag":
        return "true" if v not in ("", "0", "false", "off") else "false"
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_keyval(params, values, subst, sep: str = " = ", comment: bool = True) -> str:
    """Render a flat `key<sep>value` config file from FileParams. `sep="="` (no
    spaces) suits parsers that split on the first '=' (e.g. lorachat.conf)."""
    lines = ["# Generated by lhpc — edit via the web Config page."] if comment else []
    for p in params:
        v = values.get(p.name, p.default)
        if p.kind == "flag":
            v = "1" if str(v) not in ("", "0", "false", "off") else "0"
        lines.append(f"{subst(p.key)}{sep}{subst(str(v))}")   # key may hold {band}
    return "\n".join(lines) + "\n"


def update_toml(text: str, params, values, subst) -> str:
    """Update declared keys (by section) in an existing TOML file, preserving the
    rest. A blank value leaves the base file as-is (e.g. keep a preset default);
    a set value updates the key — uncommenting a `# key = …` line if needed."""
    want = {}
    for p in params:
        raw = subst(str(values.get(p.name, p.default)))
        if p.kind != "flag" and raw.strip() == "":
            continue                       # blank -> don't touch the base
        want[(p.section, p.key)] = _toml_value(p.kind, raw)
    lines = text.splitlines()
    section = ""
    done = set()                           # update the FIRST occurrence of each key only
    for i, line in enumerate(lines):
        st = line.strip()
        if st.startswith("[") and st.endswith("]"):
            section = st[1:-1]
            continue
        candidate = st[1:].strip() if st.startswith("#") else st
        if "=" in candidate:
            key = candidate.split("=", 1)[0].strip()
            if (section, key) in want and (section, key) not in done:
                indent = line[: len(line) - len(line.lstrip())]
                lines[i] = f"{indent}{key} = {want[(section, key)]}"
                done.add((section, key))
    return "\n".join(lines) + ("\n" if text.endswith("\n") else "")


def _yaml_value(kind: str, value: str) -> str:
    v = str(value)
    if kind == "flag":
        return "true" if v not in ("", "0", "false", "off") else "false"
    return v   # YAML bare scalar (ints/strings unquoted, as meshtasticd uses)


def update_yaml(text: str, params, values, subst) -> str:
    """Update declared `section.key` entries in a 2-space-indented YAML file,
    preserving everything else. Updates the FIRST occurrence of each key in its
    section (uncommenting a `#  key: …` line if that is the first occurrence), so
    the active value is set while commented alternative blocks are left untouched.
    Blank non-flag values leave the base as-is."""
    want = {}
    for p in params:
        raw = subst(str(values.get(p.name, p.default)))
        if p.kind != "flag" and raw.strip() == "":
            continue
        want[(p.section, p.key)] = _yaml_value(p.kind, raw)
    lines = text.splitlines()
    section = ""
    done = set()
    for i, line in enumerate(lines):
        bare = line.strip()
        if not bare or bare.startswith("---"):
            continue
        # Section header: an UNcommented top-level `Key:` with no inline value.
        if (not bare.startswith("#") and bare.endswith(":")
                and (len(line) - len(line.lstrip())) == 0 and ":" not in bare[:-1]):
            section = bare[:-1].strip()
            continue
        # Analyse a possibly-commented key line, preserving the key's own indent.
        analysed = line
        if bare.startswith("#"):
            h = line.index("#")
            analysed = line[:h] + line[h + 1:]      # drop one '#', keep indentation
        a = analysed.strip()
        if not a or a.startswith("#") or ":" not in a:
            continue
        indent = len(analysed) - len(analysed.lstrip())
        key = a.split(":", 1)[0].strip()
        sec = "" if indent == 0 else section
        if (sec, key) in want and (sec, key) not in done:
            lines[i] = f"{' ' * indent}{key}: {want[(sec, key)]}"
            done.add((sec, key))
    return "\n".join(lines) + ("\n" if text.endswith("\n") else "")


def _write_local_tables(path: Path, updates: dict) -> Path:
    """Merge `updates` (table -> {key: value}) into <runtime>/config/local.toml,
    preserving any other tables already present. Local layer is never tracked."""
    existing = _load_toml(path)
    for table, kv in updates.items():
        existing[table] = {**existing.get(table, {}), **kv}
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Local operator overrides (managed by lhpc — git-ignored)."]
    for section, table in existing.items():
        if not isinstance(table, dict):
            continue
        lines.append(f"\n[{section}]")
        for key, value in table.items():
            esc = str(value).replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key} = "{esc}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def save_operator_config(paths: Paths, callsign: str, locator: str) -> Path:
    """Persist operator identity into the runtime-local layer (git-ignored)."""
    path = paths.runtime_root / "config" / "local.toml"
    return _write_local_tables(path, {"operator": {"callsign": callsign, "locator": locator}})


def save_component_remote(paths: Paths, component_id: str, url: str) -> Path:
    """Override a component's GitHub remote in the runtime-local layer. An empty
    url clears the override (reverts to the manifest remote)."""
    path = paths.runtime_root / "config" / "local.toml"
    existing = _load_toml(path)
    remotes = dict(existing.get("remotes", {}))
    if url.strip():
        remotes[component_id] = url.strip()
    else:
        remotes.pop(component_id, None)
    # Rewrite remotes table wholesale (so clearing actually removes the key).
    existing["remotes"] = remotes
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Local operator overrides (managed by lhpc — git-ignored)."]
    for section, table in existing.items():
        if not isinstance(table, dict):
            continue
        lines.append(f"\n[{section}]")
        for key, value in table.items():
            esc = str(value).replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key} = "{esc}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


# --- per-stack user configuration (set via the web Config page) -----------

def _stack_config_path(paths: Paths, stack_id: str, band: str = "") -> Path:
    # Band-switchable stacks keep a separate config per band: "<id>@<band>.toml".
    name = f"{stack_id}@{band}.toml" if band else f"{stack_id}.toml"
    return paths.runtime_root / "config" / "stacks" / name


def load_stack_config(paths: Paths, stack_id: str, band: str = "") -> dict:
    """User-defined configuration for a stack/band (runtime-local, git-ignored)."""
    return _load_toml(_stack_config_path(paths, stack_id, band))


def save_stack_config(paths: Paths, stack_id: str, values: dict, band: str = "") -> Path:
    """Persist a stack/band's configuration (flat key/value, stored as strings)."""
    path = _stack_config_path(paths, stack_id, band)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# {stack_id} configuration (managed by lhpc — git-ignored)."]
    for key, value in values.items():
        escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'{key} = "{escaped}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
