"""Confirmed-working profile catalogue.

A confirmed-working profile pins the last KNOWN-GOOD state of a component
(commit, daemon version + TX profile, tests passed, live-test status/date,
limitations) under `<runtime>/profiles/<component>.toml`. It is the safe
fallback for rollback/repair. A component is only reported
`confirmed-working` when a profile exists AND the local source is clean and at
exactly the profile's commit — a dirty or diverged tree is never confirmed.
"""

from __future__ import annotations

import tomllib
from pathlib import Path

from .model import ConfirmedProfile
from .paths import Paths

_FLAT_STR = ("component_id", "commit", "daemon_version", "daemon_tx_profile",
             "config_schema_version", "artifact_id", "live_test_status",
             "compatibility", "limitations")


def profiles_dir(paths: Paths) -> Path:
    return paths.runtime_root / "profiles"


def load_profiles(paths: Paths) -> dict[str, ConfirmedProfile]:
    out: dict[str, ConfirmedProfile] = {}
    d = profiles_dir(paths)
    if not d.is_dir():
        return out
    for f in sorted(d.glob("*.toml")):
        try:
            with f.open("rb") as fh:
                raw = tomllib.load(fh)
        except (OSError, tomllib.TOMLDecodeError):
            continue
        if "component_id" not in raw:
            continue
        out[raw["component_id"]] = ConfirmedProfile(
            component_id=raw["component_id"],
            commit=raw.get("commit", ""),
            daemon_version=raw.get("daemon_version", ""),
            daemon_tx_profile=raw.get("daemon_tx_profile", ""),
            config_schema_version=raw.get("config_schema_version", ""),
            artifact_id=raw.get("artifact_id", ""),
            tests_passed=tuple(raw.get("tests_passed", [])),
            live_test_status=raw.get("live_test_status", ""),
            compatibility=raw.get("compatibility", ""),
            limitations=raw.get("limitations", ""),
        )
    return out


def save_profile(paths: Paths, profile: ConfirmedProfile) -> Path:
    d = profiles_dir(paths)
    d.mkdir(parents=True, exist_ok=True)
    path = d / f"{profile.component_id}.toml"
    path.write_text(_serialize(profile), encoding="utf-8")
    return path


def _serialize(p: ConfirmedProfile) -> str:
    lines = ["# Confirmed-working profile (generated by lhpc).",
             "# A dirty or diverged source is never reported as confirmed-working."]
    for key in _FLAT_STR:
        lines.append(f'{key} = "{_escape(getattr(p, key))}"')
    tests = ", ".join(f'"{_escape(t)}"' for t in p.tests_passed)
    lines.append(f"tests_passed = [{tests}]")
    return "\n".join(lines) + "\n"


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
